FROM python:3.12-slim

WORKDIR /app

# Копируем реквайременты
COPY app/requirements/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["sh", "-c", "uvicorn app.api.main:app --host 0.0.0.0 --port $API_INTERNAL_PORT --reload"]
