FROM python:3.12-slim

WORKDIR /app

# Копируем реквайременты
COPY app/requirements/requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Запуск бота
CMD ["python", "-m", "app.bot.bot"]

